#!/usr/bin/env python3
r"""
將 opencode 的供應商/模型配置遷移到 Aiapi Agent (Codex) 的 config.toml 格式
來源: C:/Users/Administrator/.config/opencode/opencode.json
目標: ~/.codex/config.toml 的 [model_providers.*] 區段

用法:
  python scripts/migrate-opencode-providers.py --input "C:/Users/Administrator/.config/opencode/opencode.json" --output examples/migrated-providers.toml
  python scripts/migrate-opencode-providers.py --apply  # 直接寫入 ~/.codex/config.toml (需安裝 toml 庫)
"""

import argparse
import json
import pathlib
import sys

# opencode provider -> codex ModelProviderInfo 映射
PROVIDER_MAP = {
    "opencode-go": {"name": "Opencode Go", "base_url": None, "env_key": None},
    "opencode-zen": {"name": "Opencode Zen", "base_url": "https://opencode.ai/zen/v1", "env_key": None},
    "gemini": {"name": "Google Gemini", "base_url": "https://generativelanguage.googleapis.com/v1beta", "env_key": "GEMINI_API_KEY"},
    "aiapi": {"name": "Aiapi", "base_url": "https://aiapi.tw/v1", "env_key": "AIAPI_API_KEY"},
    "deepseek": {"name": "DeepSeek", "base_url": "https://api.deepseek.com/v1", "env_key": "DEEPSEEK_API_KEY"},
    "anthropic": {"name": "Anthropic", "base_url": "https://api.anthropic.com", "env_key": "ANTHROPIC_API_KEY"},
    "openai": {"name": "OpenAI", "base_url": "https://api.openai.com/v1", "env_key": "OPENAI_API_KEY"},
}

def load_opencode(path: pathlib.Path) -> dict:
    text = path.read_text(encoding="utf-8")
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass
    # JSONC fallback: 移除 // 註解但避開 URL 中的 // (https://)
    import re
    # 只移除行首或空白後的 // 註解，避免破壞 https://
    text2 = re.sub(r"(^|\s)//.*", r"\1", text, flags=re.M)
    text2 = re.sub(r"/\*.*?\*/", "", text2, flags=re.S)
    return json.loads(text2)

def to_toml(providers: dict) -> str:
    lines = ["# Auto-migrated from opencode.json", "# Generated by scripts/migrate-opencode-providers.py", ""]
    for pid, cfg in providers.items():
        info = PROVIDER_MAP.get(pid, {"name": pid, "base_url": cfg.get("options", {}).get("baseURL"), "env_key": None})
        base_url = cfg.get("options", {}).get("baseURL") or cfg.get("options", {}).get("base_url") or info["base_url"]
        env_key = info["env_key"]
        # 嘗試從 apiKey 推斷環境變數
        if cfg.get("options", {}).get("apiKey"):
            env_key = env_key or f"{pid.upper()}_API_KEY"
        name = cfg.get("name") or info["name"] or pid
        # 從 npm 推斷 wire_api
        npm = cfg.get("npm", "")
        wire_api = "responses"  # Codex 只支援 responses
        lines.append(f"[model_providers.{pid}]")
        lines.append(f'name = "{name}"')
        if base_url:
            lines.append(f'base_url = "{base_url}"')
        if env_key:
            lines.append(f'env_key = "{env_key}"')
        lines.append(f'wire_api = "{wire_api}"')
        # 註解：模型列表
        models = cfg.get("models", {})
        if models:
            lines.append(f"# models: {', '.join(models.keys())}")
        lines.append("")
    return "\n".join(lines)

def main():
    ap = argparse.ArgumentParser(description="Migrate opencode providers to Codex config")
    ap.add_argument("--input", default=r"C:\Users\Administrator\.config\opencode\opencode.json", help="opencode.json path")
    ap.add_argument("--output", default="examples/migrated-providers.toml", help="output toml path")
    ap.add_argument("--apply", action="store_true", help="apply to ~/.codex/config.toml")
    args = ap.parse_args()

    inp = pathlib.Path(args.input)
    if not inp.exists():
        # fallback to opencode.jsonc
        alt = pathlib.Path(r"C:\Users\Administrator\.config\opencode\opencode.jsonc")
        if alt.exists():
            inp = alt
        else:
            print(f"Input not found: {inp}", file=sys.stderr)
            sys.exit(1)

    data = load_opencode(inp)
    providers = data.get("provider", {})
    # 同時檢查 opencode.jsonc 的 provider
    if not providers:
        print("No providers found in opencode.json", file=sys.stderr)
        sys.exit(1)

    toml_content = to_toml(providers)
    out = pathlib.Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(toml_content, encoding="utf-8")
    print(f"Wrote {out}")
    print(toml_content)

    if args.apply:
        # 合併到 ~/.codex/config.toml
        try:
            import tomllib
        except ImportError:
            try:
                import tomli as tomllib
            except ImportError:
                print("Need tomli to apply", file=sys.stderr)
                sys.exit(1)
        codex_home = pathlib.Path.home() / ".codex"
        codex_home.mkdir(exist_ok=True)
        cfg_path = codex_home / "config.toml"
        existing = ""
        if cfg_path.exists():
            existing = cfg_path.read_text(encoding="utf-8")
        # 簡單追加
        with cfg_path.open("a", encoding="utf-8") as f:
            f.write("\n" + toml_content)
        print(f"Appended to {cfg_path}")

if __name__ == "__main__":
    main()
